export const auditActionLabels: Record<string, string> = {
  project_created: "created project",
  project_updated: "updated project",
  project_deleted: "deleted project",
  member_added: "added member",
  member_removed: "removed member",
  member_role_changed: "changed member role",
  invite_created: "created invite",
  invite_deleted: "deleted invite",
  task_created: "created task",
  task_updated: "updated task",
  task_deleted: "deleted task",
  task_status_changed: "changed task status",
  task_assigned: "assigned task",
  repo_linked: "linked repository",
  repo_unlinked: "unlinked repository",
  chat_message_sent: "sent a message",
  settings_changed: "changed settings",
}
